# Generated by Django 5.0.3 on 2024-04-12 11:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notif_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=100)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('is_seen', models.BooleanField(default=False)),
                ('message', models.CharField(default='', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='IsNotified',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0)),
                ('notif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notification.notification')),
            ],
        ),
        migrations.CreateModel(
            name='RoomNotifies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_code', models.CharField(default='', max_length=6)),
                ('notif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notification.notification')),
            ],
        ),
        migrations.CreateModel(
            name='UserNotifies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0)),
                ('notif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notification.notification')),
            ],
        ),
    ]
