version: '3.9'

networks:
  ft_transcendence:
    driver: bridge

volumes:
  user_postgres_data:
  notif_postgres_data:

services:
  nginx:
    container_name: nginx_container
    env_file: .env
    build: ./web
    networks:
      - ft_transcendence
    ports:
      - '8080:443'
    depends_on:
      - db_user_management

  user_management:
    container_name: user_management_container
    build: ./user_management
    env_file: .env
      #command: gunicorn wsgi:application --bind 0.0.0.0:8001
    restart: always
    depends_on:
      - db_user_management
    networks:
      - ft_transcendence
    expose: 
      - "8001"

  notification:
    container_name: notification_container
    build: ./notification
    env_file: .env
      #command: gunicorn wsgi:application --bind 0.0.0.0:8001
    restart: always
    depends_on:
      - db_notification
    networks:
      - ft_transcendence
    expose: 
      - "8002"

  db_user_management:
    container_name: db_user_management_container
    image: postgres:15
    env_file: .env
    volumes:
      - user_postgres_data:/var/lib/postgresql/data/
    expose: 
      - "5432"
    networks:
      - ft_transcendence

  db_notification:
    container_name: db_notification
    image: postgres:15
    env_file: .env
    volumes:
      - notif_postgres_data:/var/lib/postgresql/data/
    expose:
      - "5432"
    networks:
      - ft_transcendence

  redis:
    image: redis
    container_name: redis_server
    restart: always
    networks:
      - ft_transcendence
    expose:
     - "7999"
