# Generated by Django 5.0.3 on 2024-04-17 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_player_login_otp_player_login_otp_used_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='doubleFA',
            field=models.BooleanField(default=False),
        ),
    ]
