# Generated by Django 5.0.3 on 2024-04-08 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_alter_player_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='befriends',
            name='user1',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='befriends',
            name='user2',
            field=models.IntegerField(),
        ),
    ]
