# Generated by Django 5.0.3 on 2024-04-17 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0003_player_doublefa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='doubleFA',
            new_name='twoFA',
        ),
    ]
