# Generated by Django 5.0.3 on 2024-04-09 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='play',
            name='users',
        ),
        migrations.AddField(
            model_name='play',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
    ]
