# Generated by Django 5.0.3 on 2024-04-08 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='date',
            new_name='date_begin',
        ),
        migrations.RemoveField(
            model_name='game',
            name='mode',
        ),
        migrations.RemoveField(
            model_name='game',
            name='visibility',
        ),
        migrations.AddField(
            model_name='game',
            name='date_end',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='end_status',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='room_id',
            field=models.IntegerField(default=-1),
        ),
    ]
