# Generated by Django 5.0.3 on 2024-04-10 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_remove_play_users_play_user_id'),
        ('game', '0003_game_mode_game_visibility'),
    ]

    operations = [
    ]
