# Generated by Django 5.0.3 on 2024-04-11 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_merge_20240410_1414'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='room_id',
            new_name='parent_id',
        ),
        migrations.AlterField(
            model_name='play',
            name='score',
            field=models.IntegerField(default=-1),
        ),
    ]
