# Generated by Django 5.0.3 on 2024-04-11 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_merge_20240410_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='play',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.game', unique=True),
        ),
        migrations.AlterField(
            model_name='play',
            name='user_id',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
