# Generated by Django 5.0.3 on 2024-04-11 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_alter_play_game_alter_play_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='play',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.game'),
        ),
        migrations.AlterField(
            model_name='play',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='play',
            unique_together={('game', 'user_id')},
        ),
    ]
