# Generated by Django 5.0.3 on 2024-04-04 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occupy',
            name='player_id',
            field=models.IntegerField(),
        ),
    ]
