# Generated by Django 5.0.3 on 2024-04-15 13:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='date_start',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
