# Generated by Django 5.0.3 on 2024-04-11 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_tournament_round'),
    ]

    operations = [
        migrations.RenameField(
            model_name='round',
            old_name='Tournament_id',
            new_name='tournament_id',
        ),
    ]
