# Generated by Django 5.0.3 on 2024-04-16 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_alter_round_date_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='current_round',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='total_rounds',
            field=models.IntegerField(default=0),
        ),
    ]
