# Generated by Django 5.0.3 on 2024-04-16 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_alter_tournament_current_round_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='ready_to_play',
            field=models.BooleanField(default=False),
        ),
    ]
