# Generated by Django 5.0.3 on 2024-04-09 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_notification_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomnotifies',
            name='room_id',
        ),
        migrations.AddField(
            model_name='roomnotifies',
            name='room_code',
            field=models.CharField(default='', max_length=6),
        ),
    ]
